// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  education: dynamic(() => import("./Education")),
  experiences: dynamic(() => import("./Experiences")),
  hero: dynamic(() => import("./Hero")),
  knowladges: dynamic(() => import("./Knowladges")),
};
